sonar.projectVersion=$DRONE_BUILD_NUMBER
# Name of git repo
sonar.projectKey=drt-cirium
# Name of git repo
sonar.projectName=drt-cirium
# Location of src
sonar.sources=src/main/scala
# Location of tests
sonar.tests=src/test/scala
# Location of reports
sonar.scala.scapegoat.reportPaths=target/scala-2.13/scapegoat-report/scapegoat-scalastyle.xml
sonar.scala.coverage.reportPaths=target/scala-2.13/scoverage-report/scoverage.xml
